const Data = [
     {
       id: 1,
       image: "https://i.ytimg.com/vi/N0IHdA7A11w/maxresdefault.jpg",
       name: "samsung 1s",
       category: "living",
       price: "12",
       amount: 1,
     },
   
     {
       id: 2,
       image: "https://i.ytimg.com/vi/N0IHdA7A11w/maxresdefault.jpg",
       name: "Vivo",
       category: "living",
       price: "20",
       amount: 1,
     },
     {
       id: 3,
       image: "https://i.ytimg.com/vi/N0IHdA7A11w/maxresdefault.jpg",
       name: "red mi",
       category: "living",
       price: "10",
       amount: 1,
     },
     {
       id: 4,
       image: "https://i.ytimg.com/vi/N0IHdA7A11w/maxresdefault.jpg",
       name: "nokia",
       category: "living",
       price: "50",
       amount: 1,
     },
     {
       id: 5,
       image: "https://i.ytimg.com/vi/N0IHdA7A11w/maxresdefault.jpg",
       name: "lenovo1",
       category: "living",
       price: "80",
       amount: 1,
     },
     {
       id: 6,
       image: "https://i.ytimg.com/vi/N0IHdA7A11w/maxresdefault.jpg",
       name: "iball",
       category: "living",
       price: "180",
       amount: 1,
     },
     {
       id: 7,
       image: "https://intentionaldesigns.com/wp-content/uploads/2020/03/Kitchen-Remodel-Tile-Gallerie-5.jpeg",
       name: "Windows",
       category: "kitchen",
       price: "60",
       amount: 1,
     },
     {
       id: 8,
       image: "https://intentionaldesigns.com/wp-content/uploads/2020/03/Kitchen-Remodel-Tile-Gallerie-5.jpeg",
       name: "samsung T1",
       category: "kitchen",
       price: "60",
       amount: 1,
     },
     {
       id: 9,
       image: "https://intentionaldesigns.com/wp-content/uploads/2020/03/Kitchen-Remodel-Tile-Gallerie-5.jpeg",
              name: "Samsung t2",
       category: "kitchen",
       price: "10",
       amount: 1,
     },
     {
          id: 10,
          image: "https://intentionaldesigns.com/wp-content/uploads/2020/03/Kitchen-Remodel-Tile-Gallerie-5.jpeg",
           name: "HP s5559",
          category: "kitchen",
          price: "10",
          amount: 1, 
        },
        {
          id: 11,
          image: "https://intentionaldesigns.com/wp-content/uploads/2020/03/Kitchen-Remodel-Tile-Gallerie-5.jpeg",
           name: "Dell inspiron",
          category: "kitchen",
          price: "10",
          amount: 1, 
        },
        {
          id: 12,
          image: "https://intentionaldesigns.com/wp-content/uploads/2020/03/Kitchen-Remodel-Tile-Gallerie-5.jpeg",
           name: "Asus",
          category: "kitchen",
          price: "10",
          amount: 1,
        },
        {
          id: 13,
          image: "https://th.bing.com/th/id/OIP.LBC1kuoBK9QsLfd1ls-LuQHaKd?pid=ImgDet&rs=1",
          name: "Mac book",
          category: "Bedroom",
          price: "10",
          amount: 1,
        },
   ];
   
   export default Data;

